{
 "title": "Distribució del trànsit",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "2023-12-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Distribució del trànsit procedent de la UPC agrupat per domini ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(referer) (count_over_time({referer=~\".*upc.edu\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Distribució del trànsit procedent dels principals motors de recerca ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (referer) (count_over_time({referer=~\"(www.google.com|www.bing.com|yandex.com|www.baidu.com|www.petalsearch.com)\"}[$__auto]))"
    }
   ]
  },
  {
   "title": "Trànsit procedent de motors de cerca acadèmics, xarxes acadèmiques  i enciclopèdies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (referer) (count_over_time({service_name=\"log-upcommons\", referer=~\"(scholar.google.com|scholar.google.es|www.researchgate.net|www.academia.edu|es.wikipedia.org|ca.wikipedia.org|en.wikipedia.org|recolecta.fecyt.es|explore.openaire.eu|core.ac.uk)\"}[$__auto]))"
    }
   ]
  },
  {
   "title": "Distribució del trànsit agrupat per col·lecció",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (type_recurs) (count_over_time({service_name=\"log-upcommons\"}[$__auto]))"
    }
   ]
  },
  {
   "title": "Distribució del trànsit agrupat per idioma ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (language) (count_over_time({service_name=\"log-upcommons\"}[$__auto]))"
    }
   ]
  }
 ]
}