{
 "title": "Evolució del trànsit",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "2023-12-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Evolució del trànsit procedent de la UPC agrupat per domini ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(referer) (\r\n  count_over_time({referer=~\"^(apren|futur|discovery|atenea|sso|drac|bibliotecnia).upc.edu$\"}[$__auto])\r\n)"
    }
   ]
  },
  {
   "title": "Evolució del trànsit agrupat per col·lecció",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type_recurs) (\r\n  count_over_time({type_recurs=~\"^(Exam|Bachelor thesis|Article|Doctoral thesis|Master thesis|Book|Conference report|Image|Lecture notes|Audiovisual|Conference lecture|External research report|Problem statement, exercise)$\"}[$__auto])\r\n)"
    }
   ]
  },
  {
   "title": "Evolució del trànsit agrupat per idioma",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (language) (\r\n  count_over_time({language=~\"^(spa|eng|cat)$\"}[$__auto])\r\n)"
    }
   ]
  }
 ]
}